---

- name: Ensure Atom Repository key exists
  apt_key:
    url: https://packagecloud.io/AtomEditor/atom/gpgkey
    state: present

- name: Ensure APT repository file exists
  apt_repository:
    repo: "deb https://packagecloud.io/AtomEditor/atom/any/ any main"
    state: present
    filename: atom

- name: Ensure Atom is installed
  apt:
    name: atom
    state: present
    update_cache: true
